name: sub_merge

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v4

    - name: 安装Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 加载缓存
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: 安装依赖
      run: pip install -r ./requirements.txt

    - name: 执行任务
      run: python ./TG_proxy_main.py

    - name: 确认生成文件
      run: |
        ls -l ./sub/
        ls -l ./Long_term_subscription*
        ls -l ./README.md

    - name: 提交更改
      run: |                 
        git config --local user.email '${{ secrets.EMAIL }}'
        git config --local user.name '${{ secrets.NAME }}'
        git pull origin main
        git add ./sub/*
        git add ./Long_term_subscription*
        git add ./README.md
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') sub_merge_node"
      env:
        EMAIL: ${{ secrets.EMAIL }}
        NAME: ${{ secrets.NAME }}

    - name: 推送更改
      uses: ad-m/github-push-action@master
      with:
        branch: main

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3
