name: v2-clash

on:
  #push:
  workflow_dispatch:
  schedule:
    - cron: '05 */3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: '3.11'
    - name: 加载缓存
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: 安装依赖
      run: |
        pip install -r ./requirements.txt
    - name: 执行任务
      run: |
        #python ./v2-clash.py
        python ./Test.py
    - name: 提交更改
      run: |                 
        git config --local user.email '${{ secrets.EMAIL }}'
        git config --local user.name '${{ secrets.NAME }}'
        git pull origin main
        git add ./output.yaml
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') sub_merge_node"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3
